# Generated by Django 5.2.1 on 2025-08-14 04:05

import kyc.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kycdocument',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AddField(
            model_name='kycdocument',
            name='aadhar_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='kycdocument',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='kycdocument',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='kycdocument',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='kycdocument',
            name='nationality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='kycdocument',
            name='pan_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='kycdocument',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='kycdocument',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=kyc.models.kyc_document_upload_path),
        ),
        migrations.AlterField(
            model_name='kycdocument',
            name='document_file',
            field=models.FileField(upload_to=kyc.models.kyc_document_upload_path),
        ),
    ]
