# Generated by Django 5.2.1 on 2025-08-14 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0003_userprofile_phone_verified_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kycdocument',
            old_name='aadhar_number',
            new_name='document_id',
        ),
        migrations.RenameField(
            model_name='kycdocument',
            old_name='pan_number',
            new_name='registration_number',
        ),
        migrations.RemoveField(
            model_name='kycdocument',
            name='address',
        ),
        migrations.RemoveField(
            model_name='kycdocument',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='kycdocument',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='kycdocument',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_verified',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_verified_at',
        ),
        migrations.DeleteModel(
            name='PhoneOTP',
        ),
    ]
