# Generated by Django 5.2.1 on 2025-08-14 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0004_rename_aadhar_number_kycdocument_document_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kycdocument',
            name='nationality',
        ),
        migrations.AddField(
            model_name='kycdocument',
            name='document_type',
            field=models.CharField(choices=[('passport', 'Passport'), ('driving_license', 'Driving License'), ('national_id', 'National ID'), ('birth_certificate', 'Birth Certificate'), ('utility_bill', 'Utility Bill'), ('bank_statement', 'Bank Statement'), ('employment_letter', 'Employment Letter'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
