# Generated by Django 5.2.1 on 2025-08-14 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0005_remove_kycdocument_nationality_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kycdocument',
            name='email',
        ),
    ]
