# Generated by Django 5.2.1 on 2025-08-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0006_remove_kycdocument_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='github_profile',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='language',
            field=models.CharField(choices=[('english', 'English'), ('hindi', 'Hindi'), ('spanish', 'Spanish'), ('french', 'French'), ('german', 'German'), ('chinese', 'Chinese'), ('japanese', 'Japanese'), ('arabic', 'Arabic'), ('other', 'Other')], default='english', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='linkedin_profile',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nationality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
