# Generated by Django 5.2.1 on 2025-08-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0007_userprofile_date_of_birth_userprofile_github_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='education_level',
            field=models.CharField(blank=True, choices=[('high_school', 'High School'), ('diploma', 'Diploma'), ('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('phd', 'PhD/Doctorate'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='graduation_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='institution',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profession',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profession_type',
            field=models.CharField(blank=True, choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('freelance', 'Freelance'), ('contract', 'Contract'), ('internship', 'Internship'), ('unemployed', 'Unemployed'), ('student', 'Student'), ('retired', 'Retired'), ('other', 'Other')], max_length=20),
        ),
    ]
